Import('env')

sources = env.Object([
    "main.cpp",
    "grid.cpp",
    "ant.cpp",
    "button.cpp",
    "gui.cpp",
    "simulation.cpp",
    "loadedsimulation.cpp",
    "types.cpp",
])

linkflags = []

if env['PLATFORM'] == 'nt':
    linkflags += ['-SUBSYSTEM:CONSOLE']

langton_bin = env.Program("langton", sources, LINKFLAGS=linkflags)

Return('langton_bin')